version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "lpradel"
  - package-ecosystem: 'github-actions'
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "lpradel"
